urls.py
from django.views.generic.simple import direct_to_template
from django.contrib.auth.views import *
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from finisht.views import *

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    ('^tools/$', direct_to_template, {'template': 'tools.html'}),
    ('^404/$', direct_to_template, {'template': '404.html'}),
    ('^500/$', direct_to_template, {'template': '500.html'}),
    ('^login/$', login, {'template_name': 'login.html'}),
    (r'^friends/approve/(\d+)$', approve_friend),
    (r'^friends/delete/(\d+)$', delete_friend),
    ('^logout/$', logout, {'next_page': '/'}),
    ('^toggle_friends/$', toggle_friends),
    (r'^delete/(\d+)$', delete_success),
    ('^friends/$', friends),
    ('^signup/$', signup),
    ('^$', home),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT.replace('\\','/')}),
    
)

friend/models.py
from django.contrib.auth.models import User
from django.db import models

class Friend(models.Model):
    main_user = models.IntegerField()
    friend_user = models.ForeignKey(User)
    pending = models.BooleanField()

    def __unicode__(self):
        return u'%s' %(self.main_user)

success/models.py
from django.contrib.auth.models import User
from django.db import models

class Success(models.Model):
    description = models.TextField(max_length=250)
    completed_on = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name_plural = "Successes"

    def __unicode__(self):
        return u'%s' %(self.description)

forms.py
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django import forms

class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and password.
    """
    username = forms.RegexField(max_length=30, regex=r'^\w+$')
    password1 = forms.CharField(max_length=60, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=60, widget=forms.PasswordInput)
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ("username",)
    
    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(_("A user with that username already exists."))
    
    def clean_password2(self):
        try:
            password1 = self.cleaned_data["password1"]
        except KeyError:
            raise forms.ValidationError(_("The two password fields didn't match."))
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(_("The two password fields didn't match."))
        return password2
    
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class FeedbackForm(forms.Form):
    """
    A form for feedback
    """
    message = forms.CharField()

friend/forms.py
from finisht.friend.models import Friend
from django.forms import ModelForm
from django import forms

class FriendForm(ModelForm):
    class Meta:
        model = Friend
        fields = ('friend_user',)

templates/auth_form.html
<form action="/login/" method="post" id="login-form"{% if signup %} style="display: none;"{% endif %}>
  {% if form.errors %}
    <div class="error">Sorry, I don't think that's not a valid username or password.</div>
  {% endif %}
  <div id="login-username" class="clearfix">
    <label for="username">User name:</label>
    <input type="text" name="username" value="" id="username" />
  </div>
  <div id="login-password" class="clearfix">
    <label for="password">Password:</label>
    <input type="password" name="password" value="" id="password" />
  </div>
  <div id="login-submit" class="submit clearfix">
    <input type="submit" value="Login" class="submit" />
    <input type="hidden" name="next" value="/" />
  </div>
</form>
<form action="/signup/" method="post" id="signup-form"{% if not signup %} style="display: none;"{% endif %}>
  {% if signup_form.username.errors and data %}<div class="error">{{ signup_form.username.errors }}</div>{% endif %}
  <div id="signup-username" class="clearfix">
    <label for="id_username">User name:</label>
    <input id="id_username" type="text" name="username" maxlength="30" value="{{ data.username }}" />
  </div>
  {% if signup_form.email.errors and data %}<div class="error">{{ signup_form.email.errors }}</div>{% endif %}
  <div id="signup-email" class="clearfix">
    <label for="id_email">E-mail:</label>
    <input id="id_email" type="text" name="email" value="{{ data.email }}" />
  </div>
  {% if signup_form.password1.errors and data %}<div class="error">{{ signup_form.password1.errors }}</div>{% endif %}
  <div id="signup-password1" class="clearfix">
    <label for="id_password1">Password:</label>
    <input id="id_password1" type="password" name="password1" maxlength="60" value="{{ data.password1 }}" />
  </div>
  {% if signup_form.password2.errors and data %}<div class="error">{{ signup_form.password2.errors }}</div>{% endif %}
  <div id="signup-password2" class="clearfix">
    <label for="id_password2">Again:</label>
    <input id="id_password2" type="password" name="password2" maxlength="60" value="{{ data.password2 }}"/>
  </div>
  <div id="signup-submit" class="submit clearfix">
    <input type="submit" value="Signup" class="submit" />
  </div>
</form>

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

<title>Finisht | For developers who do things.{% if title %} - {{ title }}{% endif %}</title>

<meta name="keywords" content="Finisht" />
<meta name="description" content="For developers who do things.{% if title %} - {{ title }}{% endif %}" />
<meta name="language" content="en" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="en" />

<link rel="stylesheet" href="/media/finisht.css" media="all" type="text/css" />
<link rel="icon" href="/media/images/favicon.ico" />
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">google.load("jquery", "1.2");</script>
<script type="text/javascript" src="/media/script.js"></script>
<script type="text/javascript">
  var disableFriends = {% if disable_friends %}true{% else %}false{% endif %};
</script>
{% block js %}{% endblock %}

</head>

<body{% block body_styles %}{% endblock %}>

<div id="header">
  <div class="frame">
    <a href="/"><img src="/media/images/logo.jpg" alt="See what you've done!?!" title="See what you've done!?!" /></a>
    <div id="code-promo">
      Developers!  Want to <a href="http://github.com/nicksergeant/finisht/tree/master">help build Finisht?</a>
    </div>
  </div>
</div>
<div id="content" class="frame">
  <div id="content-inner">
    {% block content %}{% endblock %}
  </div>
</div>
{% if user.is_authenticated and home %}
<div id="stats" class="frame" style="padding: 10px 0">
  {{ developer_count }} developers have finisht {{ success_count }} things since we opened up shop.  Good job!
</div>
{% endif %}
<div id="footer" class="frame">
  <div id="footer-inner">
    Finisht was scribbled together by <a href="http://lionburger.net/">Lion Burger, LLC.</a>, and is written with <a href="http://djangopony.com/">pink, pony-powered pencils</a> in <a href="http://www.djangoproject.com">Django</a>.
  </div>
</div>
{% block sub_footer %}{% endblock %}

<script type="text/javascript">
  var _gauges = _gauges || [];
  (function() {
    var t   = document.createElement('script');
    t.type  = 'text/javascript';
    t.async = true;
    t.id    = 'gauges-tracker';
    t.setAttribute('data-site-id', '4f5151d4f5a1f564a000001a');
    t.src = '//secure.gaug.es/track.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();
</script>

</body>
</html>

templates/friends.html
{% extends "base.html" %}

{% block body_styles %} id="friends"{% if user.is_authenticated %} class="logged-in"{% endif %}{% endblock %}

{% block content %}
  <div id="main" class="clearfix">
    {% include "navigation.html" %}
    {% if request.GET %}
    <div id="thanks" class="clearfix">
      <span>Sorry it didn't work out.</span>
      <a href="#" id="no-problem">It's okay</a>
    </div>
    {% endif %}
    <a href="#" id="add-friend">Add friend</a>
    <h3>Friends</h3>
    <form id="friend" method="post" action=".">
      <div id="add-friend-form" style="display: none">
        <label for="friend-input">Request to be friends with: </label>
        <select name="friend_user" id="id_friend_user">
          <option value="" selected="selected">-- select --</option>
          {% for enemy in enemies %}
            <option value="{{ enemy.id }}">{{ enemy.username }}</option>
          {% endfor %}
        </select>
        <input type="submit" id="submit" name="submit" value="Do it!" />
      </div>
    </form>
    <div id="friends-list">
    {% if friend_list %}
      <ul>
      {% for friend in friend_list %}
        <li class="clearfix">
          <p>
            {% if friend.main_username %}
              <span style="color: {% if friend.pending %}blue{% else %}black{% endif %}">{{ friend.main_username }}</span>
            {% else %}
              {{ friend.friend_user }}
            {% endif %}
            {% if friend.pending %}
              <span> (pending){% if friend.main_username %} <a href="/friends/approve/{{ friend.id }}">approve</a>{% endif %}</span>
            {% endif %}
          </p>
          <a href="/friends/delete/{{ friend.id }}" class="delete"><img src="/media/images/delete.png" alt="Delete" title="Delete" /></a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p class="loser-no-friends">You have no friends!  Start meeting people, or <a href="#add-friend" id="add-friend-link">add a friend</a>.</div>
    {% endif %}
    </div>
  </div>
{% endblock %}

{% block sub_footer %}
  {% if user.is_authenticated %}
    {% include "sub_footer.html" %}
  {% endif %}
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block body_styles %} id="homepage"{% if user.is_authenticated %} class="logged-in"{% endif %}{% endblock %}

{% block js %}
<script type="text/javascript">
  var activeLogin = 'Login';
  {% if has_friends %}
    var hasFriends = true;
  {% else %}
    var hasFriends = false;
  {% endif %}
</script>
{% endblock %}

{% block content %}
  {% if not user.is_authenticated %}
  <h1>For developers who do things.</h1>
  <p>Finisht is where you keep track of your <em>completed</em> development tasks.</p>
  <div id="main" class="clearfix">
    <div id="left">
      <div class="promo first">
        <h2>Why?</h2>
        <div class="promo-content">
          If you're like us, you finish tasks assigned to you from several sources &ndash; email, bug trackers, support tickets, face-to-face interactions, etc.  It's difficult to find a list of all the things you've done.
        </div>
      </div>
      <div class="promo">
        <img src="/media/images/what-ive-done.gif" alt="At a glance reporting" title="At a glance reporting" />
        <h2>At a glance reporting</h2>
        <div class="promo-content">
          There comes a point in time where it'd be nice to see what you've done in the past, so we made that easy.
        </div>
      </div>
      <div class="promo">
        <img src="/media/images/done.gif" alt="One-touch operation!" title="One-touch operation!" />
        <h2>One-touch operation!</h2>
        <div class="promo-content">
          No one needs another hoop to jump through in their workflow.  Just type, submit, done.
        </div>
      </div>
    </div>
    <div id="right">
      <div id="stats">
        {{ developer_count }} developers have finisht {{ success_count }} things since we opened up shop.
      </div>
      <div id="login-signup">
        <h3><span id="login">Login</span> or <a href="/signup/" id="signup">Signup</a></h3>
        {% include "auth_form.html" %}
      </div>
    </div>
  </div>
  {% else %}
  <div id="main" class="clearfix">
    {% include "navigation.html" %}
    {% if request.GET %}
    <div id="thanks" class="clearfix">
      <span>Thanks for doing that!</span>
      <a href="#" id="no-problem">No problem</a>
    </div>
    {% endif %}
    {% if delete %}
    <div id="thanks" class="clearfix">
      <span>I've deleted that for you</span>
      <a href="#" id="no-problem">Thanks</a>
    </div>
    {% endif %}
    <div id="add-success">
      <form action="/" method="post" id="done-form">
        <div class="add-success-input clearfix">
          <label for="id_description">What did you do?</label>
          <textarea id="id_description" name="description" rows="5" cols="60"></textarea>
          <input type="submit" value="Done" />
        </div>
      </form>
    </div>
    <div id="what-ive-done" class="clearfix">
      <h3>What <span id="whats-done">{% if not disable_friends and has_friends %}we've{% else %}I've{% endif %}</span> done:</h3>
      <form id="with-friends-form" method="post" action=".">
        <div id="with-friends">
          <img src="/media/images/loading.gif" alt="Loading" title="Loading" id="loading-friends" style="display: none;" />
          <input type="checkbox" id="with-friends-check"{% if not disable_friends %} checked="checked"{% endif %} /><label for="with-friends-check"> with friends</label>
        </div>
      </form>
      <div id="done-nav">
        <ul>
          <li><a href="#today" class="active" id="today-nav">Today</a></li>
          <li><a href="#yesterday" id="yesterday-nav">Yesterday</a></li>
          <li><a href="#past7days" id="past7days-nav">Past 7 days</a></li>
          <li><a href="#this-month" id="thismonth-nav">This month</a></li>
          <li><a href="#last-month" id="lastmonth-nav">Last month</a></li>
        </ul>
      </div>
      <div id="done-list">
        <div id="today">
          {% if successes_today %}
          <ul>
            {% for success in successes_today %}
              <li class="clearfix{% if success.friend %} friend{% endif %}"{% if disable_friends and success.friend %} style="display: none;"{% endif %}>
                <p class="success">
                  <span></span>
                  {% if success.friend %}{{ success.user.username }} {% endif %}{{ success.description }}
                </p>
                {% if not success.friend %}
                  <a href="/delete/{{ success.id }}">
                    <img src="/media/images/delete.png" alt="Delete" title="Delete" />
                  </a>
                {% endif %}
                <span class="done-on">{{ success.completed_on|timesince }} ago</span>
              </li>
            {% endfor %}
          </ul>
          {% else %}
          <div class="do-something">You haven't done anything today!  Get to work!</div>
          {% endif %}
        </div>
        <div id="yesterday" style="display: none;">
          {% if successes_yesterday %}
          <ul>
            {% for success in successes_yesterday %}
              <li class="clearfix{% if success.friend %} friend{% endif %}"{% if disable_friends and success.friend %} style="display: none;"{% endif %}>
                <p class="success">
                  <span></span>
                  {% if success.friend %}{{ success.user.username }} {% endif %}{{ success.description }}
                </p>
                {% if not success.friend %}
                  <a href="/delete/{{ success.id }}">
                    <img src="/media/images/delete.png" alt="Delete" title="Delete" />
                  </a>
                {% endif %}
                <span class="done-on">yesterday at {{ success.completed_on|date:"P" }}</span>
              </li>
            {% endfor %}
          </ul>
          {% else %}
          <div class="do-something">You you didn't do anything yesterday!  You fail!</div>
          {% endif %}
        </div>
        <div id="past7days" style="display: none;">
          {% if successes_this_week %}
          <ul>
            {% for success in successes_this_week %}
              <li class="clearfix{% if success.friend %} friend{% endif %}"{% if disable_friends and success.friend %} style="display: none;"{% endif %}>
                <p class="success">
                  <span></span>
                  {% if success.friend %}{{ success.user.username }} {% endif %}{{ success.description }}
                </p>
                {% if not success.friend %}
                  <a href="/delete/{{ success.id }}">
                    <img src="/media/images/delete.png" alt="Delete" title="Delete" />
                  </a>
                {% endif %}
                <span class="done-on">{{ success.completed_on|date:"D" }} at {{ success.completed_on|date:"P" }}</span>
              </li>
            {% endfor %}
          </ul>
          {% else %}
          <div class="do-something">You haven't done anything the past 7 days!  What a bum!</div>
          {% endif %}
        </div>
        <div id="thismonth" style="display: none;">
          {% if successes_this_month %}
          <ul>
            {% for success in successes_this_month %}
              <li class="clearfix{% if success.friend %} friend{% endif %}"{% if disable_friends and success.friend %} style="display: none;"{% endif %}>
                <p class="success">
                  <span></span>
                  {% if success.friend %}{{ success.user.username }} {% endif %}{{ success.description }}
                </p>
                {% if not success.friend %}
                  <a href="/delete/{{ success.id }}">
                    <img src="/media/images/delete.png" alt="Delete" title="Delete" />
                  </a>
                {% endif %}
                <span class="done-on">{{ success.completed_on|date:"D" }}, {{ success.completed_on|date:"M j" }}</span>
              </li>
            {% endfor %}
          </ul>
          {% else %}
          <div class="do-something">You haven't done anything this month!  Find a job!</div>
          {% endif %}
        </div>
        <div id="lastmonth" style="display: none;">
          {% if successes_last_month %}
          <ul>
            {% for success in successes_last_month %}
              <li class="clearfix{% if success.friend %} friend{% endif %}"{% if disable_friends and success.friend %} style="display: none;"{% endif %}>
                <p class="success">
                  <span></span>
                  {% if success.friend %}{{ success.user.username }} {% endif %}{{ success.description }}
                </p>
                {% if not success.friend %}
                  <a href="/delete/{{ success.id }}">
                    <img src="/media/images/delete.png" alt="Delete" title="Delete" />
                  </a>
                {% endif %}
                <span class="done-on">{{ success.completed_on|date:"D" }}, {{ success.completed_on|date:"M j" }}</span>
              </li>
            {% endfor %}
          </ul>
          {% else %}
          <div class="do-something">You didn't do anything last month!  Get a life!</div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endif %}
{% endblock %}

{% block sub_footer %}
  {% if user.is_authenticated %}
    {% include "sub_footer.html" %}
  {% endif %}
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block js %}
<script type="text/javascript">var activeLogin = 'Login';</script>
{% endblock %}

{% block content %}
  <div id="auth-page">
    <div id="login-signup">
      <h3><span id="login">Login</span> or <a href="/signup/" id="signup">Signup</a></h3>
      {% include "auth_form.html" %}
    </div>
  </div>
{% endblock %}

templates/maintenance.html
{% extends "base.html" %}

{% block body_styles %} id="tools"{% if user.is_authenticated %} class="logged-in"{% endif %}{% endblock %}

{% block content %}
  <div id="main" class="clearfix">
	<div class="promo first">
        <h2>Down for maintenance</h2>
        <div class="promo-content">
            <p>Finisht.com is moving servers!  We'll be back in a bit.</p>
    		<p>Go finish something so you'll have stuff to put in when we're back.</p>
        </div>
    </div>
  </div>
{% endblock %}

{% block sub_footer %}
  {% if user.is_authenticated %}
    {% include "sub_footer.html" %}
  {% endif %}
{% endblock %}

templates/navigation.html
<div id="navigation" class="clearfix">
  {% if not home %}<a class="friends-back" href="/">Back to work</a>{% endif %}
  <div id="hello">Hey there, {{ user.username }}!</div>
  <ul>
    <li><a class="friends" href="/friends/">Friends</a></li>
    <li><a class="friends" href="/tools/">Tools</a></li>
    <li><a class="logout" href="/logout/">Logout</a></li>
  </ul>
</div>

templates/signup.html
{% extends "base.html" %}

{% block js %}
<script type="text/javascript">var activeLogin = 'Signup';</script>
{% endblock %}

{% block content %}
  <div id="auth-page">
    <div id="login-signup">
      <h3><a id="login" href="/login/">Login</a> or <span id="signup">Signup</span></h3>
      {% include "auth_form.html" %}
    </div>
  </div>
{% endblock %}

templates/sub_footer.html
<div id="sub-footer">
  <div class="frame">
    <a href="http://www.djangoproject.com" title="Powered by Django"><img src="/media/images/powered-by-django.gif" alt="Powered by Django" title="Powered by Django" /></a>
  </div>
</div>

templates/tools.html
{% extends "base.html" %}

{% block body_styles %} id="tools"{% if user.is_authenticated %} class="logged-in"{% endif %}{% endblock %}

{% block content %}
  <div id="main" class="clearfix">
    {% include "navigation.html" %}
    <h3>Tools</h3>
    <div id="tools-list">
      <ul>
        <li class="clearfix">
          <p>
            Bookmarklet:
            <a href="javascript:var%20d=document,w=window,l=d.location,u='http://finisht.com/';a=function(){if(!w.open(u,'t','toolbar=0,resizable=0,status=1,width=778,height=312'))l.href=u;};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();void(0)">Done</a> <span>(drag to Firefox or Safari bookmarks)</span>
          </p>
        </li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block sub_footer %}
  {% if user.is_authenticated %}
    {% include "sub_footer.html" %}
  {% endif %}
{% endblock %}